name: EnvironmentExample

on: workflow_dispatch

jobs:
  DevDeployment:
    name: DevDeployment
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - shell: bash
        run: |
          echo ${{ env.ConnectionString }}

  ProdDeployment:
    name: ProdDeployment
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - shell: bash
        run: |
          echo ${{ env.ConnectionString }}
