name: Variables Demo

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest
    env:
      V1: Value1
      V2: Value2    
    steps:
    - name: Print value of Variable
      run: |
        echo "Value of V1 is $V1"
        echo "Value of V2 is $V2"
        echo "Value of V2 is ${{ vars.REPOVARIABLE1 }}"
    
    - name: "Say Hello Mona it's Monday"
      if: ${{ env.DAY_OF_WEEK == 'Monday' }}
      run: echo "${{ env.Greeting }} ${{ env.First_Name }}. Today is ${{ env.DAY_OF_WEEK }}!"
      env:
        First_Name: Sandeep 
